[project]
name = "stx-defi"
description = "Decentralized Finance (DeFi) Loans using STX"
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = []
[contracts.stx-defi]
path = "contracts/stx-defi.clar"
clarity_version = 3
epoch = 3.0

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
